// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI3MG6qjBja7L1R-xYNKGTj2SgyQo0QIs',
    appId: '1:907079868416:web:abd802c36c858263f178e5',
    messagingSenderId: '907079868416',
    projectId: 'bmi-tracker-bb8be',
    authDomain: 'bmi-tracker-bb8be.firebaseapp.com',
    storageBucket: 'bmi-tracker-bb8be.appspot.com',
    measurementId: 'G-2Z5FGHSN5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANOEmDgNgmO4_W0daDij0dSAEJfzFBSjY',
    appId: '1:907079868416:android:1ea71e131be315f5f178e5',
    messagingSenderId: '907079868416',
    projectId: 'bmi-tracker-bb8be',
    storageBucket: 'bmi-tracker-bb8be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4fUyw_v2Z7Gr_4iruSx39LEYNgtosTh0',
    appId: '1:907079868416:ios:51a9285fccb04b55f178e5',
    messagingSenderId: '907079868416',
    projectId: 'bmi-tracker-bb8be',
    storageBucket: 'bmi-tracker-bb8be.appspot.com',
    iosBundleId: 'com.example.bmiTracker',
  );
}
